### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by z0ph** [aws-samples/aws-cloudformation-publisher#11]
Just a question for curiosity, why deploying a bucket in each region as you could link to CloudFormation region A and use a central bucket where the template is in whatever region you want? Am I missing something here?

**Comment by HieronymusLex** [comment]
Certain artefacts must be packaged in the same region that the template is being deployed to, for example, [Lambda functions](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html)

> An Amazon S3 bucket in the same Amazon Web Services Region as your function. The bucket can be in a different Amazon Web Services account.
